import type { Node, Edge } from '@xyflow/react';
import type { FlowNodeData } from '../types';
import type { OopLang } from '../types';

function sanitize(label: string) {
  return label.replace(/[^a-zA-Z0-9_ ]/g, '').trim().replace(/\s+(.)/g, (_, c) => c.toUpperCase()) || 'step';
}
function snake(s: string) { return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, ''); }

// ── Java (original) ───────────────────────────────────────────────────
function buildJava(nodeId: string, nodes: Node[], edges: Edge[], visited: Set<string>, indent: number): string[] {
  if (visited.has(nodeId)) return [`${' '.repeat(indent)}// (loop back)`];
  visited.add(nodeId);
  const node = nodes.find(n => n.id === nodeId);
  if (!node) return [];
  const d = node.data as unknown as FlowNodeData;
  const lines: string[] = [];
  const pad = ' '.repeat(indent);

  if (d.type === 'end') { lines.push(`${pad}return;`); return lines; }
  if (d.type === 'process') { lines.push(`${pad}${sanitize(d.label)}();`); }
  else if (d.type === 'io') {
    if (d.label.toLowerCase().includes('input') || d.label.toLowerCase().includes('read')) {
      lines.push(`${pad}Scanner scanner = new Scanner(System.in);`);
      lines.push(`${pad}String input = scanner.nextLine(); // ${d.label}`);
    } else { lines.push(`${pad}System.out.println(${JSON.stringify(d.label)});`); }
  } else if (d.type === 'decision') {
    const out = edges.filter(e => e.source === nodeId);
    const yes = out.find(e => (e.label as string)?.toLowerCase() === 'yes' || e.sourceHandle === 'yes');
    const no  = out.find(e => e !== yes);
    lines.push(`${pad}if (/* ${d.label} */) {`);
    if (yes) lines.push(...buildJava(yes.target, nodes, edges, new Set(visited), indent + 4));
    if (no)  { lines.push(`${pad}} else {`); lines.push(...buildJava(no.target, nodes, edges, new Set(visited), indent + 4)); }
    lines.push(`${pad}}`);
    return lines;
  }
  for (const e of edges.filter(e => e.source === nodeId))
    lines.push(...buildJava(e.target, nodes, edges, visited, indent));
  return lines;
}

function genJavaFlow(nodes: Node[], edges: Edge[]): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const out: string[] = ['// Generated by UML→Code', '', 'public class FlowProcess {', '', '    public static void main(String[] args) {'];
  if (start) out.push(...buildJava(start.id, nodes, edges, new Set(), 8));
  else out.push('        // Connect a Start node to begin');
  out.push('    }', '');
  procs.forEach(n => {
    const d = n.data as unknown as FlowNodeData;
    const nm = sanitize(d.label);
    out.push(`    private static void ${nm}() {`, `        // TODO: implement ${d.label}`, '    }', '');
  });
  out.push('}');
  return out.join('\n');
}

// ── Python ────────────────────────────────────────────────────────────
function buildPy(nodeId: string, nodes: Node[], edges: Edge[], visited: Set<string>, indent: number): string[] {
  if (visited.has(nodeId)) return [`${' '.repeat(indent)}# (loop back)`];
  visited.add(nodeId);
  const node = nodes.find(n => n.id === nodeId);
  if (!node) return [];
  const d = node.data as unknown as FlowNodeData;
  const lines: string[] = [];
  const pad = ' '.repeat(indent);

  if (d.type === 'end') { lines.push(`${pad}return`); return lines; }
  if (d.type === 'process') lines.push(`${pad}${snake(sanitize(d.label))}()`);
  else if (d.type === 'io') {
    if (d.label.toLowerCase().includes('input')) lines.push(`${pad}data = input("${d.label}: ")`);
    else lines.push(`${pad}print(${JSON.stringify(d.label)})`);
  } else if (d.type === 'decision') {
    const out = edges.filter(e => e.source === nodeId);
    const yes = out.find(e => (e.label as string)?.toLowerCase() === 'yes' || e.sourceHandle === 'yes');
    const no  = out.find(e => e !== yes);
    lines.push(`${pad}if ${d.label.toLowerCase().replace(/[^a-z0-9_]/g, '_') || 'condition'}:`);
    if (yes) lines.push(...buildPy(yes.target, nodes, edges, new Set(visited), indent + 4));
    else lines.push(`${pad}    pass`);
    if (no)  { lines.push(`${pad}else:`); lines.push(...buildPy(no.target, nodes, edges, new Set(visited), indent + 4)); }
    return lines;
  }
  for (const e of edges.filter(e => e.source === nodeId))
    lines.push(...buildPy(e.target, nodes, edges, visited, indent));
  return lines;
}

function genPythonFlow(nodes: Node[], edges: Edge[]): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const out: string[] = ['# Generated by UML→Code', '', 'def main():'];
  if (start) { const body = buildPy(start.id, nodes, edges, new Set(), 4); out.push(...body.length ? body : ['    pass']); }
  else out.push('    # Connect a Start node to begin', '    pass');
  out.push('', '');
  procs.forEach(n => {
    const nm = snake(sanitize((n.data as unknown as FlowNodeData).label));
    out.push(`def ${nm}():`, `    # TODO: implement`, '    pass', '');
  });
  out.push('', "if __name__ == '__main__':", '    main()');
  return out.join('\n');
}

// ── C++ ───────────────────────────────────────────────────────────────
function buildCpp(nodeId: string, nodes: Node[], edges: Edge[], visited: Set<string>, indent: number): string[] {
  if (visited.has(nodeId)) return [`${' '.repeat(indent)}// (loop back)`];
  visited.add(nodeId);
  const node = nodes.find(n => n.id === nodeId);
  if (!node) return [];
  const d = node.data as unknown as FlowNodeData;
  const lines: string[] = [];
  const pad = ' '.repeat(indent);

  if (d.type === 'end') { lines.push(`${pad}return;`); return lines; }
  if (d.type === 'process') lines.push(`${pad}${sanitize(d.label)}();`);
  else if (d.type === 'io') {
    if (d.label.toLowerCase().includes('input')) lines.push(`${pad}std::string input; std::cin >> input; // ${d.label}`);
    else lines.push(`${pad}std::cout << ${JSON.stringify(d.label)} << std::endl;`);
  } else if (d.type === 'decision') {
    const out = edges.filter(e => e.source === nodeId);
    const yes = out.find(e => (e.label as string)?.toLowerCase() === 'yes' || e.sourceHandle === 'yes');
    const no  = out.find(e => e !== yes);
    lines.push(`${pad}if (/* ${d.label} */) {`);
    if (yes) lines.push(...buildCpp(yes.target, nodes, edges, new Set(visited), indent + 4));
    if (no)  { lines.push(`${pad}} else {`); lines.push(...buildCpp(no.target, nodes, edges, new Set(visited), indent + 4)); }
    lines.push(`${pad}}`);
    return lines;
  }
  for (const e of edges.filter(e => e.source === nodeId))
    lines.push(...buildCpp(e.target, nodes, edges, visited, indent));
  return lines;
}

function genCppFlow(nodes: Node[], edges: Edge[]): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const out: string[] = ['// Generated by UML→Code', '#include <iostream>', '#include <string>', '', ''];
  procs.forEach(n => {
    out.push(`void ${sanitize((n.data as unknown as FlowNodeData).label)}();`);
  });
  out.push('', 'int main() {');
  if (start) out.push(...buildCpp(start.id, nodes, edges, new Set(), 4));
  else out.push('    // Connect a Start node to begin');
  out.push('    return 0;', '}', '');
  procs.forEach(n => {
    const nm = sanitize((n.data as unknown as FlowNodeData).label);
    out.push(`void ${nm}() {`, `    // TODO: implement ${nm}`, '}', '');
  });
  return out.join('\n');
}

// ── TypeScript / JavaScript ───────────────────────────────────────────
function buildTs(nodeId: string, nodes: Node[], edges: Edge[], visited: Set<string>, indent: number): string[] {
  if (visited.has(nodeId)) return [`${' '.repeat(indent)}// (loop back)`];
  visited.add(nodeId);
  const node = nodes.find(n => n.id === nodeId);
  if (!node) return [];
  const d = node.data as unknown as FlowNodeData;
  const lines: string[] = [];
  const pad = ' '.repeat(indent);

  if (d.type === 'end') { lines.push(`${pad}return;`); return lines; }
  if (d.type === 'process') lines.push(`${pad}${sanitize(d.label)}();`);
  else if (d.type === 'io') {
    if (d.label.toLowerCase().includes('input')) lines.push(`${pad}const input = prompt('${d.label}');`);
    else lines.push(`${pad}console.log(${JSON.stringify(d.label)});`);
  } else if (d.type === 'decision') {
    const out = edges.filter(e => e.source === nodeId);
    const yes = out.find(e => (e.label as string)?.toLowerCase() === 'yes' || e.sourceHandle === 'yes');
    const no  = out.find(e => e !== yes);
    lines.push(`${pad}if (/* ${d.label} */) {`);
    if (yes) lines.push(...buildTs(yes.target, nodes, edges, new Set(visited), indent + 2));
    if (no)  { lines.push(`${pad}} else {`); lines.push(...buildTs(no.target, nodes, edges, new Set(visited), indent + 2)); }
    lines.push(`${pad}}`);
    return lines;
  }
  for (const e of edges.filter(e => e.source === nodeId))
    lines.push(...buildTs(e.target, nodes, edges, visited, indent));
  return lines;
}

function genTsFlow(nodes: Node[], edges: Edge[], isJs = false): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const ret = isJs ? '' : ': void';
  const fnKw = isJs ? 'function' : 'function';
  const out: string[] = [`// Generated by UML→Code`, '', `${fnKw} main()${ret} {`];
  if (start) out.push(...buildTs(start.id, nodes, edges, new Set(), 2));
  else out.push('  // Connect a Start node to begin');
  out.push('}', '');
  procs.forEach(n => {
    const nm = sanitize((n.data as unknown as FlowNodeData).label);
    out.push(`${fnKw} ${nm}()${ret} {`, `  // TODO: implement ${nm}`, '}', '');
  });
  out.push('main();');
  return out.join('\n');
}

// ── C# ────────────────────────────────────────────────────────────────
function genCsharpFlow(nodes: Node[], edges: Edge[]): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const out: string[] = ['// Generated by UML→Code', 'using System;', '', 'public class FlowProcess {', '    public static void Main(string[] args) {'];
  if (start) out.push(...buildJava(start.id, nodes, edges, new Set(), 8).map(l => l.replace('System.out.println', 'Console.WriteLine').replace('new Scanner(System.in)', 'Console.ReadLine()')));
  else out.push('        // Connect a Start node to begin');
  out.push('    }', '');
  procs.forEach(n => {
    const nm = sanitize((n.data as unknown as FlowNodeData).label);
    out.push(`    private static void ${nm}() {`, `        // TODO: implement ${nm}`, '    }', '');
  });
  out.push('}');
  return out.join('\n');
}

// ── Kotlin ────────────────────────────────────────────────────────────
function genKotlinFlow(nodes: Node[], edges: Edge[]): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const out: string[] = ['// Generated by UML→Code', '', 'fun main() {'];
  if (start) out.push(...buildTs(start.id, nodes, edges, new Set(), 4).map(l => l.replace('console.log', 'println').replace('prompt(', 'readLine()?.let { it }; // ')));
  else out.push('    // Connect a Start node to begin');
  out.push('}', '');
  procs.forEach(n => {
    const nm = sanitize((n.data as unknown as FlowNodeData).label);
    out.push(`fun ${nm}() {`, `    // TODO: implement ${nm}`, '}', '');
  });
  return out.join('\n');
}

// ── Go ────────────────────────────────────────────────────────────────
function genGoFlow(nodes: Node[], edges: Edge[]): string {
  const flow = nodes.filter(n => n.type === 'flowNode');
  const start = flow.find(n => (n.data as unknown as FlowNodeData).type === 'start');
  const procs = flow.filter(n => (n.data as unknown as FlowNodeData).type === 'process');
  const out: string[] = ['// Generated by UML→Code', 'package main', '', 'import "fmt"', '', 'func main() {'];
  if (start) out.push(...buildCpp(start.id, nodes, edges, new Set(), 4).map(l => l.replace('std::cout <<', 'fmt.Println(').replace('<< std::endl;', ')').replace('std::string input; std::cin >> input;', 'var input string; fmt.Scan(&input)')));
  else out.push('    // Connect a Start node to begin');
  out.push('}', '');
  procs.forEach(n => {
    const nm = sanitize((n.data as unknown as FlowNodeData).label);
    out.push(`func ${nm}() {`, `    // TODO: implement ${nm}`, '}', '');
  });
  return out.join('\n');
}

// ── Dispatcher ─────────────────────────────────────────────────────────
export function generateFlowCode(nodes: Node[], edges: Edge[], lang: OopLang = 'java'): string {
  const flowNodes = nodes.filter(n => n.type === 'flowNode');
  if (flowNodes.length === 0) return '// No flowchart nodes defined yet.';
  switch (lang) {
    case 'python':     return genPythonFlow(nodes, edges);
    case 'cpp':        return genCppFlow(nodes, edges);
    case 'csharp':     return genCsharpFlow(nodes, edges);
    case 'typescript': return genTsFlow(nodes, edges, false);
    case 'javascript': return genTsFlow(nodes, edges, true);
    case 'kotlin':     return genKotlinFlow(nodes, edges);
    case 'go':         return genGoFlow(nodes, edges);
    default:           return genJavaFlow(nodes, edges);
  }
}
