import type { Node, Edge } from '@xyflow/react';
import type { SequenceNodeData } from '../types';
import type { OopLang } from '../types';

/* ── helpers ────────────────────────────────────────────────────── */
function camel(s: string) {
  return s.replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
          .replace(/[^a-zA-Z0-9]/g, '');
}
function snake(s: string) {
  return camel(s).replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}
function pascal(s: string) { const c = camel(s); return c.charAt(0).toUpperCase() + c.slice(1); }
function lower(s: string)  { const c = camel(s); return c.charAt(0).toLowerCase() + c.slice(1); }

/** Sort edges by sourceHandle "r-N" index (Y position on lifeline) */
function sortedMessages(allEdges: Edge[], allNodes: Node[]): Edge[] {
  const seqIds = new Set(allNodes.filter(n => n.type === 'sequenceNode').map(n => n.id));
  const msgs = allEdges.filter(e => seqIds.has(e.source));
  return [...msgs].sort((a, b) => {
    const parseH = (h: string | null | undefined, fallback: number) => {
      if (!h) return fallback * 100;
      const m = h.match(/[rl]-?(\d+)/);
      return m ? parseInt(m[1]) : fallback * 100;
    };
    return parseH(a.sourceHandle, msgs.indexOf(a)) - parseH(b.sourceHandle, msgs.indexOf(b));
  });
}

function msgLabel(e: Edge, i: number) {
  return ((e.label as string) || (e.data?.label as string) || `message${i + 1}`).trim();
}

function nameMap(nodes: Node[]) {
  return new Map(nodes.filter(n => n.type === 'sequenceNode').map(n => [
    n.id, (n.data as unknown as SequenceNodeData).label || 'Participant'
  ]));
}

/* ── Java ────────────────────────────────────────────────────────── */
function genJava(nodes: Node[], edges: Edge[]): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '// No lifelines yet.\n// Add Lifeline nodes to the canvas.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);

  const params = lifelines.map(([, name]) => `${pascal(name)} ${lower(name)}`).join(',\n            ');
  const lines = [
    `// Generated by UML→Code — Sequence Diagram`,
    `// Generated: ${now}`,
    `// Participants: ${lifelines.map(([, n]) => n).join(', ')}`,
    ``,
    `public class SequenceInteraction {`,
    ``,
    `    public static void execute(`,
    `            ${params}) {`,
    ``,
  ];

  msgs.forEach((e, i) => {
    const from = lower(map.get(e.source) ?? 'source');
    const to   = lower(map.get(e.target) ?? 'target');
    const msg  = lower(camel(msgLabel(e, i)));
    lines.push(`        // Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`        ${to}.${msg}(${from});`);
    lines.push(``);
  });

  if (!msgs.length) lines.push(`        // Connect lifelines with message arrows to generate interaction code`);
  lines.push(`    }`, `}`);
  return lines.join('\n');
}

/* ── Python ──────────────────────────────────────────────────────── */
function genPython(nodes: Node[], edges: Edge[]): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '# No lifelines yet.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);
  const params = lifelines.map(([, name]) => snake(name)).join(', ');

  const lines = [
    `# Generated by UML→Code — Sequence Diagram`,
    `# Generated: ${now}`,
    `# Participants: ${lifelines.map(([, n]) => n).join(', ')}`,
    ``,
    `def execute(${params}):`,
  ];
  msgs.forEach((e, i) => {
    const from = snake(map.get(e.source) ?? 'source');
    const to   = snake(map.get(e.target) ?? 'target');
    const msg  = snake(msgLabel(e, i));
    lines.push(`    # Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`    result_${i + 1} = ${to}.${msg}(${from})`);
    lines.push(``);
  });
  if (!msgs.length) lines.push(`    pass  # Connect lifelines with message arrows`);
  lines.push(``, `if __name__ == '__main__':`, `    pass  # Instantiate participants and call execute()`);
  return lines.join('\n');
}

/* ── TypeScript / JavaScript ─────────────────────────────────────── */
function genTs(nodes: Node[], edges: Edge[], isJs = false): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '// No lifelines yet.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);
  const ret = isJs ? '' : ': void';
  const params = isJs
    ? lifelines.map(([, name]) => lower(name)).join(', ')
    : lifelines.map(([, name]) => `${lower(name)}: ${pascal(name)}`).join(', ');

  const lines = [
    `// Generated by UML→Code — Sequence Diagram`,
    `// Generated: ${now}`,
    ``,
    `function execute(${params})${ret} {`,
  ];
  msgs.forEach((e, i) => {
    const from = lower(map.get(e.source) ?? 'source');
    const to   = lower(map.get(e.target) ?? 'target');
    const msg  = lower(camel(msgLabel(e, i)));
    lines.push(`  // Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`  const result${i + 1} = ${to}.${msg}(${from});`);
    lines.push(``);
  });
  if (!msgs.length) lines.push(`  // Connect lifelines with message arrows to generate interaction code`);
  lines.push(`}`);
  return lines.join('\n');
}

/* ── C# ──────────────────────────────────────────────────────────── */
function genCsharp(nodes: Node[], edges: Edge[]): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '// No lifelines yet.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);
  const params = lifelines.map(([, name]) => `${pascal(name)} ${lower(name)}`).join(',\n        ');

  const lines = [
    `// Generated by UML→Code — Sequence Diagram`,
    `// Generated: ${now}`,
    `using System;`,
    ``,
    `public class SequenceInteraction`,
    `{`,
    `    public static void Execute(`,
    `        ${params})`,
    `    {`,
  ];
  msgs.forEach((e, i) => {
    const from = lower(map.get(e.source) ?? 'source');
    const to   = lower(map.get(e.target) ?? 'target');
    const msg  = pascal(msgLabel(e, i));
    lines.push(`        // Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`        ${to}.${msg}(${from});`);
    lines.push(``);
  });
  if (!msgs.length) lines.push(`        // Connect lifelines with message arrows to generate interaction code`);
  lines.push(`    }`, `}`);
  return lines.join('\n');
}

/* ── Kotlin ──────────────────────────────────────────────────────── */
function genKotlin(nodes: Node[], edges: Edge[]): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '// No lifelines yet.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);
  const params = lifelines.map(([, name]) => `${lower(name)}: ${pascal(name)}`).join(', ');

  const lines = [
    `// Generated by UML→Code — Sequence Diagram`,
    `// Generated: ${now}`,
    ``,
    `fun execute(${params}) {`,
  ];
  msgs.forEach((e, i) => {
    const from = lower(map.get(e.source) ?? 'source');
    const to   = lower(map.get(e.target) ?? 'target');
    const msg  = lower(camel(msgLabel(e, i)));
    lines.push(`    // Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`    val result${i + 1} = ${to}.${msg}(${from})`);
    lines.push(``);
  });
  if (!msgs.length) lines.push(`    // Connect lifelines with message arrows to generate interaction code`);
  lines.push(`}`);
  return lines.join('\n');
}

/* ── Go ──────────────────────────────────────────────────────────── */
function genGo(nodes: Node[], edges: Edge[]): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '// No lifelines yet.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);
  const params = lifelines.map(([, name]) => `${lower(name)} *${pascal(name)}`).join(', ');

  const lines = [
    `// Generated by UML→Code — Sequence Diagram`,
    `// Generated: ${now}`,
    `package main`,
    ``,
    `func execute(${params}) {`,
  ];
  msgs.forEach((e, i) => {
    const from = lower(map.get(e.source) ?? 'source');
    const to   = lower(map.get(e.target) ?? 'target');
    const msg  = pascal(msgLabel(e, i));
    lines.push(`\t// Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`\t${to}.${msg}(${from})`);
    lines.push(``);
  });
  if (!msgs.length) lines.push(`\t// Connect lifelines with message arrows to generate interaction code`);
  lines.push(`}`);
  return lines.join('\n');
}

/* ── Ruby ────────────────────────────────────────────────────────── */
function genRuby(nodes: Node[], edges: Edge[]): string {
  const map = nameMap(nodes);
  const lifelines = [...map.entries()];
  if (!lifelines.length) return '# No lifelines yet.';
  const msgs = sortedMessages(edges, nodes);
  const now = new Date().toISOString().slice(0, 10);
  const params = lifelines.map(([, name]) => snake(name)).join(', ');

  const lines = [
    `# Generated by UML→Code — Sequence Diagram`,
    `# Generated: ${now}`,
    ``,
    `def execute(${params})`,
  ];
  msgs.forEach((e, i) => {
    const from = snake(map.get(e.source) ?? 'source');
    const to   = snake(map.get(e.target) ?? 'target');
    const msg  = snake(msgLabel(e, i));
    lines.push(`  # Step ${i + 1}: ${from} ──► ${to} : ${msg}`);
    lines.push(`  result_${i + 1} = ${to}.${msg}(${from})`);
    lines.push(``);
  });
  if (!msgs.length) lines.push(`  # Connect lifelines with message arrows to generate interaction code`);
  lines.push(`end`);
  return lines.join('\n');
}

/* ── dispatcher ─────────────────────────────────────────────────── */
export function generateSequenceCode(nodes: Node[], edges: Edge[], lang: OopLang = 'java'): string {
  const seqNodes = nodes.filter(n => n.type === 'sequenceNode');
  if (!seqNodes.length) return '// No sequence diagram nodes yet.\n// Add Lifeline (Actor/Object) nodes to the canvas, then connect them with message arrows.';
  switch (lang) {
    case 'python':     return genPython(nodes, edges);
    case 'typescript': return genTs(nodes, edges, false);
    case 'javascript': return genTs(nodes, edges, true);
    case 'csharp':     return genCsharp(nodes, edges);
    case 'kotlin':     return genKotlin(nodes, edges);
    case 'go':         return genGo(nodes, edges);
    case 'ruby':       return genRuby(nodes, edges);
    default:           return genJava(nodes, edges);
  }
}
